<?php

/**
 * @file
 * Install, update and uninstall functions for the ecc_microsites_redirect_dashboard module.
 */

/**
 * Implements hook_install().
 */
function ecc_microsites_redirect_dashboard_install() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_uninstall().
 */
function ecc_microsites_redirect_dashboard_uninstall() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}
