domain_path.settings:
  type: config_object
  mapping:
    entity_types:
      label: Enabled entity types for domain paths
      type: sequence
      sequence:
        type: string
    hide_path_alias_ui:
      label: Hide the default URL alias UI
      type: boolean
    language_method:
      label: The method of language detection
      type: string