stages:
  - build
  - development
  - development-postdeploy
  - preproduction
  - preproduction-postdeploy
  - production
  - production-postdeploy

build-and-push-images:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_PASS: ""
  before_script:
    - docker login -u${DOCKER_USER} -p${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker pull ${DOCKER_REGISTRY}/microsites-nginx-drupal || true
    - docker pull ${DOCKER_REGISTRY}/microsites-drupal-fpm || true
    - docker pull ${DOCKER_REGISTRY}/microsites-nginx-redirect || true
    - docker build -t ${DOCKER_REGISTRY}/microsites-drupal-fpm${tag} -t microsites-drupal-fpm -f Dockerfile-drupal .
    - docker build -t ${DOCKER_REGISTRY}/microsites-nginx-drupal${tag} -t microsites-nginx-drupal -f Dockerfile-nginx .
    - docker build -t ${DOCKER_REGISTRY}/microsites-nginx-redirect${tag} -t microsites-nginx-redirect -f Dockerfile-nginx-redirect .
    - docker push ${DOCKER_REGISTRY}/microsites-nginx-drupal${tag}
    - docker push ${DOCKER_REGISTRY}/microsites-drupal-fpm${tag}
    - docker push ${DOCKER_REGISTRY}/microsites-nginx-redirect${tag}
  only:
    - develop
    - /^release\//
    - feature/pipeline-improvements

deploy-to-dev:
  image: mcr.microsoft.com/azure-cli
  stage: development
  needs: ["build-and-push-images"]
  environment:
    name: development
    url: https://essex-gov.nomensa.xyz/
  before_script:
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "Creating new revision of Container App"
    - |
      cat > revision.yml <<EOF
      properties:
        template:
          revisionSuffix: ${CI_PIPELINE_ID}
          containers:
            - image: acreccuksdev.azurecr.io/microsites-nginx-drupal$tag
              name: nginx
              resources:
                cpu: 0.25
                memory: 0.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              env:
              - name: X_ROBOTS_TAG
                value: noindex
            - image: acreccuksdev.azurecr.io/microsites-drupal-fpm$tag
              name: drupal
              resources:
                cpu: 0.75
                memory: 1.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              - mountPath: /drupal/data/default/private
                volumeName: privsharevol
              env:
              - name: MYSQL_HOST
                value: mariadb-ecc-uks-dev.mariadb.database.azure.com
              - name: MYSQL_USER
                value: mariadb-root
              - name: MYSQL_DATABASE
                value: drupal_microsites
              - name: MYSQL_PASSWORD
                secretRef: mysql-password
              - name: OPENID_CONNECT_PARAMS
                secretRef: openid-connect-params
      EOF
    - az containerapp revision copy --name microsites --resource-group rg-ecc-microsites-uks-dev --yaml revision.yml --subscription "Essex County Council (Microsites)"
  rules:
    - when: manual

drush-deploy-dev:
  image: mcr.microsoft.com/azure-cli
  stage: development-postdeploy
  needs: ["deploy-to-dev"]
  before_script:
    - apk add socat
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
    - az account set --subscription "Essex County Council (Microsites)"
  script:
    - timeout 1200 socat EXEC:'az containerapp exec --command /drupal/deploy.sh --name microsites --container drupal --resource-group rg-ecc-microsites-uks-dev',pty,setsid,ctty STDIO,ignoreeof
  rules:
    - when: manual

deploy-to-preprod:
  image: mcr.microsoft.com/azure-cli
  stage: preproduction
  needs: ["deploy-to-dev"]
  environment:
    name: preproduction
    url: https://essex-gov-pp.nomensa.xyz/
  before_script:
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
  script:
    - echo "Importing image from Development  into Pre-Production"
    - az acr import --force --name acreccukspre --source acreccuksdev.azurecr.io/microsites-nginx-drupal:${CI_COMMIT_REF_SLUG} --image microsites-nginx-drupal:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - az acr import --force --name acreccukspre --source acreccuksdev.azurecr.io/microsites-drupal-fpm:${CI_COMMIT_REF_SLUG} --image microsites-drupal-fpm:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - az acr import --force --name acreccukspre --source acreccuksdev.azurecr.io/microsites-nginx-redirect:${CI_COMMIT_REF_SLUG} --image microsites-nginx-redirect:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - |
      cat > revision.yml <<EOF
      properties:
        template:
          revisionSuffix: ${CI_PIPELINE_ID}
          containers:
            - image: acreccukspre.azurecr.io/microsites-nginx-drupal:${CI_COMMIT_REF_SLUG}
              name: nginx
              resources:
                cpu: 0.25
                memory: 0.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              env:
              - name: X_ROBOTS_TAG
                value: noindex
              - name: LIMITED_BETA_MODE
                value: 1
            - image: acreccukspre.azurecr.io/microsites-drupal-fpm:${CI_COMMIT_REF_SLUG}
              name: drupal
              resources:
                cpu: 0.75
                memory: 1.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              env:
              - name: MYSQL_HOST
                value: mariadb-ecc-uks-pre.mariadb.database.azure.com
              - name: MYSQL_USER
                value: mariadb-root
              - name: MYSQL_DATABASE
                value: drupal_microsites
              - name: MYSQL_PASSWORD
                secretRef: mysql-password
              - name: OPENID_CONNECT_PARAMS
                secretRef: openid-connect-params
      EOF
    - echo "Creating new revision of Container App"
    - az containerapp revision copy --name microsites --resource-group rg-ecc-microsites-uks-pre --yaml revision.yml --subscription "Essex County Council (Microsites)"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\//'
      when: manual

drush-deploy-preprod:
  image: mcr.microsoft.com/azure-cli
  stage: preproduction-postdeploy
  needs: ["deploy-to-preprod"]
  before_script:
    - apk add socat
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
    - az account set --subscription "Essex County Council (Microsites)"
  script:
    - timeout 1200 socat EXEC:'az containerapp exec --command /drupal/deploy.sh --name microsites --container drupal --resource-group rg-ecc-microsites-uks-pre',pty,setsid,ctty STDIO,ignoreeof
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\//'
      when: manual

deploy-to-prod:
  image: mcr.microsoft.com/azure-cli
  stage: production
  needs: ["deploy-to-preprod"]
  environment:
    name: production
    url: https://essex.gov.uk/
  before_script:
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
  script:
    - echo "Importing image from Pre-Production into Production"
    - az acr import --force --name acreccuksprod --source acreccukspre.azurecr.io/microsites-nginx-drupal:${CI_COMMIT_REF_SLUG} --image microsites-nginx-drupal:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - az acr import --force --name acreccuksprod --source acreccukspre.azurecr.io/microsites-drupal-fpm:${CI_COMMIT_REF_SLUG} --image microsites-drupal-fpm:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - az acr import --force --name acreccuksprod --source acreccukspre.azurecr.io/microsites-nginx-redirect:${CI_COMMIT_REF_SLUG} --image microsites-nginx-redirect:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - echo "Creating new revision of Container App"
    - |
      cat > revision.yml <<EOF
      properties:
        template:
          revisionSuffix: ${CI_PIPELINE_ID}
          containers:
            - image: acreccuksprod.azurecr.io/microsites-nginx-drupal:${CI_COMMIT_REF_SLUG}
              name: nginx
              resources:
                cpu: 0.25
                memory: 0.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              env:
              - name: X_ROBOTS_TAG
                value: noindex
              - name: LIMITED_BETA_MODE
                value: 1
            - image: acreccuksprod.azurecr.io/microsites-drupal-fpm:${CI_COMMIT_REF_SLUG}
              name: drupal
              resources:
                cpu: 0.75
                memory: 1.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              env:
              - name: MYSQL_HOST
                value: mariadb-ecc-uks-prod.mariadb.database.azure.com
              - name: MYSQL_USER
                value: mariadb-root
              - name: MYSQL_DATABASE
                value: drupal_microsites
              - name: MYSQL_PASSWORD
                secretRef: mysql-password
              - name: OPENID_CONNECT_PARAMS
                secretRef: openid-connect-params
      EOF
    - az containerapp revision copy --name microsites --resource-group rg-ecc-microsites-uks-prod --yaml revision.yml --subscription "Essex County Council (Microsites)"
    - az containerapp revision copy --name microsites-nginx-redirect --resource-group rg-ecc-microsites-redirect-uks-prod --image acreccuksprod.azurecr.io/microsites-nginx-redirect:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Microsites)"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\//'
      when: manual

drush-deploy-prod:
  image: mcr.microsoft.com/azure-cli
  stage: production-postdeploy
  needs: ["deploy-to-prod"]
  before_script:
    - apk add socat
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
    - az account set --subscription "Essex County Council (Microsites)"
  script:
    - timeout 1200 socat EXEC:'az containerapp exec --command /drupal/deploy.sh --name microsites --container drupal --resource-group rg-ecc-microsites-uks-prod',pty,setsid,ctty STDIO,ignoreeof
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\//'
      when: manual
