domain_group.settings:
  type: config_object
  label: Settings
  mapping:
    unique_group_access:
      type: boolean
      label: 'Unique group access'
    restricted_login:
      type: boolean
      label: 'Restrict login to Default Domain'
domain.record.*.third_party.domain_group:
  type: mapping
  label: 'Domain Group settings'
  mapping:
    group:
      type: integer
      label: 'Domain Group ID'
