# Config schema for the Field Formatter Range module.

field.formatter.third_party.field_formatter_range:
  type: mapping
  label: 'Field Formatter Range settings'
  mapping:
    order:
      type: integer
      label: 'Type of order'
    limit:
      type: integer
      label: 'Display items'
    offset:
      type: integer
      label: 'Skip items'
