<?php

use \Drupal\Core\Url;
use Drupal\group\Entity\Group;
use Drupal\group\Context\GroupContext;
use Drupal\Core\DependencyInjection\ContainerInjectionInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * @file
 * Primary module hooks for LGD Theme Fixes module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function lgd_theme_fixes_page_attachments_alter(&$attachments) {
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  if (\Drupal::service('theme.manager')->getActiveTheme()->getName() == $admin_theme) {
    // For some reason the CKEditor link dialog is not working in the admin.
    // It's z-index is too low for it to be visible.
    $attachments['#attached']['library'][] = 'lgd_theme_fixes/ckeditor_link_dialog';
  }
}

/**
 * Implements hook_form_alter()
 *
 * Adding in reset buttons to views because Views is misbehaving.
 * Something unknown was setting reset buttons #access to FALSE.
 */
function lgd_theme_fixes_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'views_exposed_form') {
    if ($form['#id'] === 'views-exposed-form-group-nodes-microsite-page') {
      if (!empty($form['actions']['reset'])) {
        $form['actions']['reset']['#access'] = TRUE;
      }
    }
    if ($form['#id'] === 'views-exposed-form-group-media-page-1') {
      if (!empty($form['actions']['reset'])) {
        $form['actions']['reset']['#access'] = TRUE;
      }
    }
  }

  if ($form['#form_id'] === 'localgov_alert_banner_localgov_alert_banner_status_form') {
    $form['actions']['submit']['#submit'][] = 'microsite_create_alert_redirect_submit';
  }
}

function microsite_create_alert_redirect_submit($form, &$form_state) {
  /** @var \Drupal\domain\DomainInterface $current_domain */
  $current_domain = \Drupal::service('domain.negotiator')->getActiveDomain();
  if (!empty($current_domain)) {
    $group_uuid = $current_domain->getThirdPartySetting('group_context_domain', 'group_uuid');
    if (!empty($group_uuid)) {
      /** @var \Drupal\group\Entity\GroupInterface $group */
      $group = \Drupal::service('entity.repository')
        ->loadEntityByUuid('group', $group_uuid);
    }
  }
  $destination_path = '/group/' . $group->id() . '/alert-banners';
  $destination_url = Url::fromUserInput($destination_path);
  $form_state->setRedirectUrl($destination_url);
}
