<?php

use \Drupal\Core\Url;

/**
 * @file
 * Primary module hooks for LGD Theme Fixes module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function lgd_theme_fixes_page_attachments_alter(&$attachments) {
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  if (\Drupal::service('theme.manager')->getActiveTheme()->getName() == $admin_theme) {
    // For some reason the CKEditor link dialog is not working in the admin.
    // It's z-index is too low for it to be visible.
    $attachments['#attached']['library'][] = 'lgd_theme_fixes/ckeditor_link_dialog';
  }
}

/**
 * Implements hook_form_alter()
 *
 * Adding in reset buttons to views because Views is misbehaving.
 * Something unknown was setting reset buttons #access to FALSE.
 */
function lgd_theme_fixes_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'views_exposed_form') {
    if ($form['#id'] === 'views-exposed-form-group-nodes-microsite-page') {
      if (!empty($form['actions']['reset'])) {
        $form['actions']['reset']['#access'] = TRUE;
      }
    }
    if ($form['#id'] === 'views-exposed-form-group-media-page-1') {
      if (!empty($form['actions']['reset'])) {
        $form['actions']['reset']['#access'] = TRUE;
      }
    }
  }

  if ($form['#form_id'] === 'localgov_alert_banner_localgov_alert_banner_add_form') {
    $destination_url = Url::fromUserInput('/admin/content/alert-banner');
    $form_state->setRedirectUrl($destination_url);
  }
}
