https://{all}/:
  cache:
    cookies: ["/^SSESS.*/"]
    default_ttl: 2000
    enabled: true
    headers:
    - Accept
    - Accept-Language
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: false
  type: upstream
  upstream: app:http
https://www.{all}/:
  redirects:
    expires: -1s
    paths: {}
  to: https://{all}/
  type: redirect
https://*.{all}/:
  type: upstream
  upstream: app:http

