include: 
  ################
  # DrupalCI includes: 
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

#
# Start custom overrides.
#

variables:
  #  Disable default phpunit job in favor of the d9/10 variants below.
  SKIP_PHPUNIT: 1
  _PHPUNIT_EXTRA: --verbose

# Run variations of composer job.
composer:
  parallel:
    matrix:
      - _TARGET_PHP: [ "8.1", "8.2" ]
        _TARGET_CORE: [ "$CORE_STABLE" ]

phpcs:
  # Set allow_failure to false so that the test fails for coding standards faults.
  allow_failure: false
  dependencies:
    - "composer: [8.1, $CORE_STABLE]"

composer-lint:
  dependencies:
    - "composer: [8.1, $CORE_STABLE]"

eslint:
  dependencies:
    - "composer: [8.1, $CORE_STABLE]"

stylelint:
  dependencies:
    - "composer: [8.1, $CORE_STABLE]"

.phpunit-local:
  variables:
    SKIP_PHPUNIT: 0

phpunit-php8.1:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: "8.1"
            _TARGET_CORE: $CORE_STABLE
  variables:
    _TARGET_PHP: "8.1"
  extends:
    - .phpunit-base
    - .phpunit-local

phpunit-php8.2:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: "8.2"
            _TARGET_CORE: $CORE_STABLE
  variables:
    _TARGET_PHP: "8.2"
  extends:
    - .phpunit-base
    - .phpunit-local